name: Manual update channel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - shell: bash
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          # Get the last commit hash
          commit=$(git log -1 --pretty=format:"%H")
          echo "commit: " $commit
          # Get the list of files changed in the last commit
          files_changed=$(git diff-tree --no-commit-id --name-only -r $commit | grep ".md")
          if [ ! -f $files_changed ]; then
            echo "No .md file in commit: " $commit
            exit 1
            else: echo Some hp      
          fi
          echo "files_changed: " $files_changed
          # Get the last file changed
          new_md=$(echo "$files_changed" | tail -n 1)
          echo "NEW>> " $new_md
          char_num=$(cat new_md | wc -c)
          echo "NUM: " $char_num
          if [ char_num -ge 4096 ]; then 
            echo "The text to big: " $((4096 - $char_num))
            exit 1
          fi 
          if [ -f $new_md ]; then
            curl -s -X POST  https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_channel_id -d parse_mode=Markdown --data-urlencode text@$new_md
          fi
