name: Manual update channel

on: 
  workflow_dispatch:

jobs:
  update_channel:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Send Markdown file to Telegram
        shell: bash
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          # Get the list of changed files in the last commit
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)

          echo "Changed files: $changed_files"

          # Find the first changed .md file (adjust if you need to handle multiple)
          new_md=$(echo "$changed_files" | grep -m1 '\.md$' || true)

          if [[ -z "$new_md" ]]; then
            echo "No .md file found in the last commit."
            exit 1
          fi

          echo "Markdown file to post: $new_md"

          # Check file size
          char_num=$(wc -c < "$new_md")
          echo "Character count: $char_num"

          if (( char_num >= 4096 )); then
            echo "The text is too big by $((char_num - 4096)) characters."
            exit 1
          fi

          # Send message to Telegram
          curl -s -X POST "https://api.telegram.org/bot$tg_bot_token/sendMessage" \
            -d chat_id="$tg_channel_id" \
            -d parse_mode=Markdown \
            --data-urlencode text@"$new_md"
