# ==================================================================================================
# File: .github/workflows/manual_tg_update.yml
#
# Workflow Name: Manual update channel
#
# Description:
#   This GitHub Actions workflow is triggered manually via `workflow_dispatch`. It detects 
#   the first modified Markdown (.md) file from the latest commit, checks the file size to 
#   ensure it doesn't exceed Telegram's 4096 character limit, and sends its content to a specified 
#   Telegram channel using the Telegram Bot API.
#
# Use Case:
#   This workflow is useful for manually triggering updates to a Telegram channel when a 
#   Markdown file (e.g., changelog, documentation) is updated in a commit.
#
# Trigger:
#   - Event: workflow_dispatch
#   - This allows manual triggering of the workflow via GitHub Actions UI.
#
# Required Secrets:
#   - TELEGRAM_BOT_TOKEN: Token from @BotFather to send messages via Telegram Bot API
#   - TELEGRAM_CHANNEL_ID: Telegram channel ID where the message will be sent
#
# Assumptions:
#   - At least one Markdown file (.md) is modified in the commit.
#   - The file content is under Telegram's 4096 character limit for a message.
#
# Limitations:
#   - Only the first `.md` file found in the commit will be processed.
#   - If the file size exceeds Telegram's limit, the workflow will fail.
#
# Author: Dmitry Troshenkov <troshenkov.d@gmail.com>
# Last updated: 2025-04-19
# ==================================================================================================

name: Manual update channel

on: 
  workflow_dispatch:  # Trigger this workflow manually through GitHub UI

jobs:
  update_channel:
    runs-on: ubuntu-latest  # Using Ubuntu for the runner
    environment: production  # The environment this job will run in

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Fetch repository content
        with:
          fetch-depth: 2  # Fetch the last two commits for comparison

      - name: Send Markdown file to Telegram
        shell: bash
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Secret for the Telegram bot token
          tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}  # Secret for the Telegram channel ID
        run: |
          # Get the list of changed files in the last commit
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)

          echo "Changed files: $changed_files"  # Print the list of changed files

          # Find the first changed .md file (adjust if you need to handle multiple)
          new_md=$(echo "$changed_files" | grep -m1 '\.md$' || true)

          if [[ -z "$new_md" ]]; then
            echo "No .md file found in the last commit."
            exit 1  # Exit if no .md file is found
          fi

          echo "Markdown file to post: $new_md"  # Print the Markdown file to be posted

          # Check the file size
          char_num=$(wc -c < "$new_md")
          echo "Character count: $char_num"  # Print the character count of the file

          if (( char_num >= 4096 )); then
            echo "The text is too big by $((char_num - 4096)) characters."
            exit 1  # Exit if the file exceeds the Telegram character limit
          fi

          # Send the file content to the Telegram channel
          curl -s -X POST "https://api.telegram.org/bot$tg_bot_token/sendMessage" \
            -d chat_id="$tg_channel_id" \
            -d parse_mode=Markdown \
            --data-urlencode text@"$new_md"