# ==================================================================================================
# File: .github/workflows/post_to_tg_channel.yml
#
# Workflow Name: Post News to Telegram
#
# Description:
#   This GitHub Actions workflow posts each Markdown news file in the `updates/` directory
#   to a Telegram channel. Messages are split if longer than 4,096 characters.
#   If the Markdown includes image URLs or document links, the media is sent separately before the text.
#   After posting, the files are moved to the `posted/` directory.
#
# Improvements:
#   - Splits messages over 4,096 chars into chunks.
#   - Sends images (Markdown ![](url)) before text.
#   - Sends documents (PDF, DOC, etc.) if included in Markdown.
#   - Sends inline buttons with each post.
#   - Archives processed files to avoid duplicates.
#   - Improved error handling with more specific error reporting.
#   - Added manual trigger for the workflow.
#   - Enforces Telegram API limits.
#
# Required Secrets:
#   - TELEGRAM_BOT_TOKEN: Token from @BotFather to send messages via Telegram Bot API.
#   - TELEGRAM_CHAT_ID: Telegram chat ID where the message will be sent.
#
# Author: Dmitry Troshenkov <troshenkov.d@gmail.com>
# Last updated: 2025-04-22
# ==================================================================================================

name: Post News to Telegram

# Trigger the workflow on a schedule or manually
on:
  schedule:
    # Run the workflow every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment
    environment: production # Environment with Telegram secrets

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Ensure required directories exist
    - name: Prepare directories
      run: |
        mkdir -p updates
        mkdir -p posted

    # Step 3: Validate Telegram secrets
    - name: Validate Telegram secrets
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        ERRORS=""

        if [ -z "${TELEGRAM_BOT_TOKEN}" ]; then
          ERRORS+="Error: TELEGRAM_BOT_TOKEN is not set. Please configure the secret and try again.\n"
        fi

        if [ -z "${TELEGRAM_CHAT_ID}" ]; then
          ERRORS+="Error: TELEGRAM_CHAT_ID is not set. Please configure the secret and try again.\n"
        fi

        if [ -n "$ERRORS" ]; then
          echo -e "$ERRORS"
          exit 1
        fi

    # Step 4: Post each news item to Telegram
    - name: Post each news item to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        NEWS_DIR="updates"
        POSTED_DIR="posted"

        if [ -z "$(ls -A $NEWS_DIR/*.md 2>/dev/null)" ]; then
          echo "$(date) - No news files found."
          exit 0
        fi

        for FILE in $NEWS_DIR/*.md; do
          echo "$(date) - Processing file: $FILE"

          MESSAGE=$(cat "$FILE")

          if [ -z "$MESSAGE" ]; then
            echo "$(date) - Warning: $FILE is empty. Skipping."
            continue
          fi

          # Extract image URLs
          IMAGE_URLS=$(grep -oP '!\[.*?\]\(\K[^\)]+(?=\))' "$FILE")

          # Send each image (up to 10 MB limit for remote URLs assumed)
          for IMAGE_URL in $IMAGE_URLS; do
            echo "$(date) - Sending image: $IMAGE_URL"
            RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d photo="$IMAGE_URL")
            if [[ "$RESPONSE" != *'"ok":true'* ]]; then
              ERROR_MSG=$(echo "$RESPONSE" | jq '.description')
              echo "$(date) - Failed to send image: $IMAGE_URL. Response: $ERROR_MSG"
              exit 1
            fi
          done

          # Extract document URLs (PDF, DOC, DOCX, PPTX)
          DOCUMENT_URLS=$(grep -oP 'https?://[^\s]+\.pdf|doc|docx|pptx' "$FILE")

          # Send documents
          for DOCUMENT_URL in $DOCUMENT_URLS; do
            echo "$(date) - Sending document: $DOCUMENT_URL"
            RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d document="$DOCUMENT_URL")
            if [[ "$RESPONSE" != *'"ok":true'* ]]; then
              ERROR_MSG=$(echo "$RESPONSE" | jq '.description')
              echo "$(date) - Failed to send document: $DOCUMENT_URL. Response: $ERROR_MSG"
              exit 1
            fi
          done

          # Remove image markdown from message
          CLEANED_MSG=$(echo "$MESSAGE" | sed -E 's/!\[.*?\]\(.*?\)//g')

          # Send message in chunks of max 4096 characters (Telegram limit)
          CHUNK_SIZE=4096
          while [ ${#CLEANED_MSG} -gt 0 ]; do
            CHUNK="${CLEANED_MSG:0:$CHUNK_SIZE}"
            CLEANED_MSG="${CLEANED_MSG:$CHUNK_SIZE}"
            RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d parse_mode="MarkdownV2" \
              --data-urlencode text="$CHUNK")
            if [[ "$RESPONSE" != *'"ok":true'* ]]; then
              ERROR_MSG=$(echo "$RESPONSE" | jq '.description')
              echo "$(date) - Failed to send message chunk. Response: $ERROR_MSG"
              exit 1
            fi
          done

          # Send inline buttons (example link to full article)
          INLINE_BUTTONS='{"inline_keyboard":[[{"text":"Read More","url":"http://example.com"}]]}'
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="MarkdownV2" \
            --data-urlencode text="See more" \
            -d "reply_markup=$INLINE_BUTTONS")

          if [[ "$RESPONSE" != *'"ok":true'* ]]; then
            ERROR_MSG=$(echo "$RESPONSE" | jq '.description')
            echo "$(date) - Failed to send inline button. Response: $ERROR_MSG"
            exit 1
          fi

          echo "$(date) - Finished sending: $FILE"

          # Move the file to the posted directory
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          BASENAME=$(basename "$FILE")
          mv "$FILE" "$POSTED_DIR/${TIMESTAMP}_$BASENAME"
        done

        echo "All news items have been posted."

    # Step 5: Commit and push processed files to the repository
    - name: Commit and push processed files
      run: |
        GITHUB_USER_NAME="GitHub Actions Bot"
        GITHUB_USER_EMAIL="actions@github.com"

        # Configure Git user information
        git config user.name "${GITHUB_USER_NAME}"
        git config user.email "${GITHUB_USER_EMAIL}"

        # Stash any unstaged changes to avoid conflicts
        git stash --include-untracked

        # Pull the latest changes from the remote repository with rebase
        git pull --rebase origin main

        # Apply the stashed changes back
        git stash pop || echo "No stashed changes to apply."

        # Stage all changes (e.g., moved files in the posted directory)
        git add posted/

        # Commit the changes with the current date in the message
        git commit -m "Move processed news files to posted directory on $(date +'%Y-%m-%d')" || echo "No changes to commit."

        # Push the changes to the repository
        git push origin main
