# ==================================================================================================
# File: .github/workflows/post_to_tg_channel.yml
#
# Workflow Name: Post News to Telegram
#
# Description:
#   This workflow automates the process of posting Markdown news files from the `updates/` directory
#   to a Telegram channel. It delegates specific tasks, such as secret validation and Markdown file
#   processing, to external scripts for modularity and maintainability.
#
# Workflow Steps:
#   1. Checkout the repository.
#   2. Validate required secrets for Telegram using `scripts/validate_secrets.sh`.
#   3. Process Markdown files and post their content to Telegram using `scripts/process_markdown_files.sh`.
#   4. Upload logs as GitHub Actions artifacts for debugging.
#   5. Commit and push archived files and logs back to the repository.
#
# Triggers:
#   - Scheduled daily at 8 AM UTC.
#   - Manual trigger via workflow dispatch.
#
# Required Secrets:
#   - TELEGRAM_BOT_TOKEN: Telegram Bot API token.
#   - TELEGRAM_CHAT_ID: Target Telegram chat ID.
#
# Scripts Used:
#   - `scripts/validate_secrets.sh`: Validates required secrets for Telegram.
#   - `scripts/process_markdown_files.sh`: Processes Markdown files and posts to Telegram.
#   - `scripts/git_setup.sh`: Configures Git for committing and pushing changes.
#
# Author: Dmitry Troshenkov <troshenkov.d@gmail.com>
# Last Updated: 2025-04-24
# ==================================================================================================

name: Post News to Telegram

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8 AM UTC
  workflow_dispatch:     # Allow manual triggering of the workflow

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest
    environment: production

    steps:
# ----------------------------------------
# Step 1: Checkout the repository
# ----------------------------------------
    - name: Checkout code
      uses: actions/checkout@v3

# ----------------------------------------
# Step 2: Validate required secrets
# ----------------------------------------
    - name: Validate required Telegram secrets
      run: |
        chmod +x scripts/validate_secrets.sh
        scripts/validate_secrets.sh
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

# ----------------------------------------
# Step 3: Process Markdown files
# ----------------------------------------
    - name: Post news files to Telegram
      run: |
        chmod +x scripts/process_markdown_files.sh
        scripts/process_markdown_files.sh
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

# ----------------------------------------
# Step 4: Upload logs
# ----------------------------------------
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: telegram-logs
        path: logs/
        retention-days: 7

# ----------------------------------------
# Step 5: Commit and push changes
# ----------------------------------------

    # Commit and push archived files
    - name: Commit and push archived files
      run: |
        chmod +x scripts/git_setup.sh
        scripts/git_setup.sh
        git stash --include-untracked
        git pull --rebase --no-edit origin main
        git stash pop || echo "No stashed changes to apply."
        git add posted/
        git commit -m "Move processed news files to posted directory on $(date +'%Y-%m-%d')" || echo "No changes to commit."
        git push origin main

    # Commit and push logs
    - name: Commit and push logs
      run: |
        chmod +x scripts/git_setup.sh
        scripts/git_setup.sh
        git add logs/
        git commit -m "Add Telegram logs on $(date +'%Y-%m-%d')" || echo "No log changes to commit."
        git push origin main

