# ==================================================================================================
# File: .github/workflows/self_test.yml
#
# Workflow Name: Self-Test Workflow for Markdown Validation
#
# Description:
#   This workflow validates Markdown files in the `updates` folder and ensures proper functionality
#   of the Telegram posting logic. It triggers manually or when changes are made to the `updates` folder.
#
# Triggers:
#   - Manual trigger via `workflow_dispatch`.
#   - On changes to the `updates` folder.
#
# Artifacts:
#   - Logs generated during the test are uploaded as artifacts and retained for 7 days.
#
# Author: Dmitry Troshenkov <troshenkov.d@gmail.com>
# Last Updated: 2025-04-27
# ==================================================================================================

name: Self Test Workflow

on:
  workflow_dispatch:  # Allow manual triggering of the workflow
  push:
    paths:
      - "updates/**"  # Trigger when files in the `updates` folder are changed

jobs:
  self_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up environment variables
      - name: Set up environment variables
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Environment variables set for Telegram integration."

      # Step 3: Validate Markdown files in the `updates` folder
      - name: Validate Markdown files
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Validating Markdown files in the 'updates' folder..."
          chmod +x scripts/validate_markdown.sh
          NEWS_DIR=updates ./scripts/validate_markdown.sh
          echo "Validation completed successfully."

      # Step 4: Preview Telegram messages (Dry Run)
      - name: Preview Telegram messages
        run: |
          echo "Previewing Telegram messages..."
          DRY_RUN=true TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
          NEWS_DIR="updates" ./scripts/validate_markdown.sh
          echo "Preview completed. No messages were sent to Telegram."

      # Step 5: Check for logs
        - name: Check for logs
        run: |
          if [ ! -d "/tmp/markdown_test_tQCI/logs/" ] || [ -z "$(ls -A /tmp/markdown_test_tQCI/logs/)" ]; then
            echo "No logs found. Skipping artifact upload."
            exit 0
          fi

      # Step 6: Upload test logs
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: self-test-logs
          path: /tmp/markdown_test_tQCI/logs/
          retention-days: 7
          if-no-files-found: warn