# ==================================================================================================
# File: .github/workflows/tg_edit.yml
#
# Workflow Name: Edit channel
#
# Description:
#   This GitHub Actions workflow is triggered when a pull request is either opened or reopened.
#   It searches for the first Markdown (.md) file changed in the commit, verifies the file's 
#   existence and size (under 4096 characters), and sends its contents to a specified Telegram 
#   chat using the Telegram Bot API.
#
# Use Case:
#   Automatically notify a Telegram chat about updates to documentation or changelog when a 
#   pull request is opened or reopened.
#
# Trigger:
#   - Event: pull_request
#   - Types: [opened, reopened]
#
# Required Secrets:
#   - TELEGRAM_BOT_TOKEN: Token from @BotFather to send messages via Telegram Bot API
#   - TELEGRAM_CHAT_ID: Telegram chat ID or @username where the message will be sent
#
# Assumptions:
#   - At least one Markdown file (.md) is modified in the commit.
#   - The file content is under Telegram's 4096 character limit for a message.
#
# Limitations:
#   - Only the first `.md` file found in the commit will be processed.
#   - The workflow does not handle cases where the content exceeds Telegram's message limit 
#     (messages longer than 4096 characters will cause failure).
#
# Author: Dmitry Troshenkov <troshenkov.d@gmail.com>
# Last updated: 2025-04-19
# ==================================================================================================

name: Edit channel

on:
  pull_request:
    types: [opened, reopened]  # Trigger workflow when PR is opened or reopened

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the latest 2 commits to ensure we can detect changes

      - name: Send Markdown update to Telegram
        shell: bash
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Find the first .md file changed in the latest commit
          new_md=$(git diff-tree --no-commit-id --name-only -r HEAD | grep -m1 '\.md$' || true)

          # Exit if no markdown file is found
          if [[ -z "$new_md" ]]; then
            echo "No Markdown (.md) file found in the last commit."
            exit 0
          fi

          echo "Found Markdown file: $new_md"

          # Check if the file exists and verify size
          if [[ -f "$new_md" ]]; then
            char_num=$(wc -c < "$new_md")  # Get the character count
            echo "Character count: $char_num"

            # Check if the file size exceeds Telegram's limit (4096 characters)
            if (( char_num >= 4096 )); then
              echo "The text is too big by $((char_num - 4096)) characters."
              exit 1
            fi

            # Send the file content to Telegram
            curl -s -X POST \
              -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
              "https://api.telegram.org/bot$tg_bot_token/sendMessage" \
              -d chat_id="$tg_chat_id" \
              -d parse_mode=Markdown \
              --data-urlencode text@"$new_md"
          else
            echo "File does not exist: $new_md"
            exit 1
          fi