name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a multi-line script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          #!/bin/bash
          export TELEGRAM_BOT_TOKEN=${{ TELEGRAM_BOT_TOKEN }}
          #TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}
          #TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          #set $TELEGRAM_BOT_TOKEN
          #set $TELEGRAM_CHANNEL_ID
          #set $TELEGRAM_CHAT_ID
          #
          #commit=$(git log -1 --pretty=format:"%H")
          #Get the list of files changed in the last commit
          #files_changed=$(git diff-tree --no-commit-id --name-only -r ${commit} | head -n 1 | grep  ".md")
          #Get the last file changed
          #last_file=$(echo "$files_changed" | tail -n 1)
          #TG update
          #if [  ${last_file} ]{
          #  curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHANNEL_ID} -d parse_mode=Markdown --data-urlencode text@${last_file}
          #}
          if [ ! ${TELEGRAM_BOT_TOKEN} ] { exit 2 }
          if [ ! ${TELEGRAM_CHANNEL_ID} ] { exit 3 }
          if [ ! ${TELEGRAM_CHAT_ID} ] { exit 4 }
          #curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="New commit pushed to the repository"

