name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - shell: bash
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          #tg_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          #!/bin/bash
          commit=$(git log -1 --pretty=format:"%H")
          new_md=$(git diff-tree --no-commit-id --name-only -r $commit  | grep  ".md" )
          echo $tg_bot_token
          echo $tg_channel_id
          # Print the raw content of the last file changed
          msg=$(git show $commit:$new_md)
          echo $msg
          #TG update
          #if [  $last_file ]; then
          curl -s -X POST https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_channel_id -d parse_mode=Markdown --data-urlencode text@$last_file
          #fi
          #curl -s -X POST https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_chat_id -d text="New commit pushed to the repository"
