name: CI
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          #!/bin/bash
          #
          #commit=$(git log -1 --pretty=format:"%H")
          #Get the list of files changed in the last commit
          #files_changed=$(git diff-tree --no-commit-id --name-only -r ${commit} | head -n 1 | grep  ".md")
          #Get the last file changed
          #last_file=$(echo "$files_changed" | tail -n 1)
          #TG update
          #if [  ${last_file} ]{
          #curl -s -X POST https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_channel_id -d parse_mode=Markdown --data-urlencode text@${last_file}
          #}
           echo "TG_BT_TKN = " ${{ secrets.TELEGRAM_BOT_TOKEN }}
           echo "fg_bot_token= " $tg_bot_token
          #curl -s -X POST https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_chat_id -d text="New commit pushed to the repository"
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          # tg_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
