name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          #!/bin/bash
          #
          commit=$(git log -1 --pretty=format:"%H")
          echo $commit
          #Get the list of files changed in the last commit
          file_changed=$(git diff-tree --no-commit-id --name-only -r ${commit} | head -n 1 | grep  ".md")
          echo $file_changed
          #Get the last file changed
          file=$(echo "$file_changed" | tail -n 1)
          echo $file
          #TG update
          if [  ${file} ]; then
          curl -s -X POST https://api.telegram.org/bot${tg_bot_token}/sendMessage -d chat_id=${tg_channel_id} -d parse_mode=Markdown --data-urlencode text@${file}
          fi
          #curl -s -X POST https://api.telegram.org/bot$tg_bot_token/sendMessage -d chat_id=$tg_chat_id -d text="New commit pushed to the repository"
        env:
          tg_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          #tg_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
